/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsAndConditionsIndexRouteImport } from './routes/terms-and-conditions/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as ContactUsIndexRouteImport } from './routes/contact-us/index'
import { Route as ActivitiesIndexRouteImport } from './routes/activities/index'
import { Route as AboutUsIndexRouteImport } from './routes/about-us/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsIndexRoute = TermsAndConditionsIndexRouteImport.update({
  id: '/terms-and-conditions/',
  path: '/terms-and-conditions/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsIndexRoute = ContactUsIndexRouteImport.update({
  id: '/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsIndexRoute
  '/activities': typeof ActivitiesIndexRoute
  '/contact-us': typeof ContactUsIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/terms-and-conditions': typeof TermsAndConditionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsIndexRoute
  '/activities': typeof ActivitiesIndexRoute
  '/contact-us': typeof ContactUsIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/terms-and-conditions': typeof TermsAndConditionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/contact-us/': typeof ContactUsIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/terms-and-conditions/': typeof TermsAndConditionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/activities'
    | '/contact-us'
    | '/gallery'
    | '/terms-and-conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/activities'
    | '/contact-us'
    | '/gallery'
    | '/terms-and-conditions'
  id:
    | '__root__'
    | '/'
    | '/about-us/'
    | '/activities/'
    | '/contact-us/'
    | '/gallery/'
    | '/terms-and-conditions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
  ContactUsIndexRoute: typeof ContactUsIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  TermsAndConditionsIndexRoute: typeof TermsAndConditionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions/': {
      id: '/terms-and-conditions/'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us/': {
      id: '/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
  ContactUsIndexRoute: ContactUsIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  TermsAndConditionsIndexRoute: TermsAndConditionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
